config/routes.rb
Rails.application.routes.draw do

  resources :site_current_dates
  resources :temp_deps
  resources :temp_week_days
  resources :temp_sps

  resources :departments
  resources :week_days
  resources :spaces
  resources :seats

  resources :reservations
  resources :quick_reservations
  resources :favourite_spaces

  resources :tasks

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", passwords: "passwords", confirmations: "confirmations", sessions: "sessions" }

  root "home#index"

  # Generali
  get "/home", to: "home#index"
  post '/home', to: 'home#index', as: 'get_meteo_info'
  get "/leaflet_osm_map", to: "leaflet_osm#index"
  get "/personal_area", to: "personal_area#index"
  get "/informations", to: "informations#index"

  # Accessibili dall'area personale utente
  get "/user_reservations", to: "reservations#reserved"
  get "/favourite_spaces", to: "favourite_spaces#index"

  # Admin
  get "/management", to: "management#index"

  # Dipartimenti
  get "/make_department", to: "temp_deps#new"
  post '/make_department', to: 'temp_deps#set_temp_wd', as: 'set_temp_wd'
  get "/manager_department", to: "departments#manager_department"
  post '/manager_department', to: 'departments#manager_map_initializer', as: 'manager_map_initializer'

  # Prenotazioni
  get "/make_reservation", to: "reservations#new"
  post '/make_reservation', to: 'reservations#set_department', as: 'set_department'
  post '/user_reservations', to: 'reservations#make_actions', as: 'make_actions'
  get "/make_quick_res", to: "quick_reservations#make_quick_res"

  post "/find_on_map", to:"home#find_on_map"

  resources :users do       # CONTROLLA LE MAIL DI CONFERMA E IN CASO DI ASSENZA PER NUOVA REGISTRAZIONE NE INVIA UNA (CONTROLLARE application_mailer PER ULTERIORI DETTAGLI)
    member do
      get :confirm_email
      patch :ban
      patch :set_manager
      patch :manager_req
      patch :get_user_coord
    end
  end

  devise_scope :user do     # CONTROLLA IL TIMEOUT DELLA SESSIONE DELL'UTENTE 
    get   "/check_session_timeout"    => "session_timeout#check_session_timeout"
    get   "/session_timeout"          => "session_timeout#render_timeout"
  end

end

app/models/favourite_space.rb
class FavouriteSpace < ApplicationRecord
    belongs_to :user, required: :true       #
    belongs_to :department, required: :true # Permette di inserire un riferimento delle tabelle alle quali è vincolata
    belongs_to :space, required: :true      #
end

app/controllers/favourite_spaces_controller.rb
class FavouriteSpacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favourite_space, only: %i[ show edit update destroy ]

  # Mostra all'utente la lista dei suoi spazi preferiti
  def index
    @favourite_spaces = FavouriteSpace.where(user_id: current_user.id)
  end

  def create
    @favourite_space = FavouriteSpace.new(favourite_space_params)

    respond_to do |format|
      if @favourite_space.save
        format.html { redirect_to request.referrer, notice: "Lo spazio '"+@favourite_space.typology+" - "+@favourite_space.name+"' è stato aggiunto ai preferiti." }
      else
        format.html { redirect_to request.referrer, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    typ = @favourite_space.typology
    nm = @favourite_space.space_name
    @favourite_space.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: "Lo spazio '"+typ+" - "+nm+"' è stato rimosso dai preferiti." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite_space
      @favourite_space = FavouriteSpace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_space_params
      params.require(:favourite_space).permit(:user_id, :department_id, :space_id, :email, :dep_name, :typology, :space_name)
    end
end

app/helpers/favourite_spaces_helper.rb
module FavouriteSpacesHelper
end

app/views/favourite_spaces/index.html.erb
<!DOCTYPE html>
<html lang="it">
<head>

	<title> Spazi Preferiti - Spacebook </title>

	<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
	<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap.min.css">

	<script>
		$(document).ready(function () {
			$('#datatableSpaziPreferiti').DataTable({
				dom: '<"row"<"col"t>><"row mt-1"<"col"p>>',
				scrollX: true,
				filter: 'false',
				pagingType: "simple_numbers",
				pageLength: 7,
				language: {
					zeroRecords: 'Nessuno spazio preferito',
					paginate: {
						first:    '<i class="bi bi-caret-left-fill"></i>',
						previous: '<i class="bi bi-arrow-left-circle"></i>',
						next:     '<i class="bi bi-arrow-right-circle"></i>',
						last:     '<i class="bi bi-caret-right-fill"></i>'
					}
				}
			});
		});
	</script>

</head>

<body>

<div class="row mt-4 justify-content-center">
	<div class="col-lg-7">
		<div class="card">
			<div class="card-header text-center">
				<label class="h2 my-3"> Spazi preferiti </label>
			</div>
			<div class="card-body">
				<table id="datatableSpaziPreferiti" class="display table-responsive table-striped table-hover" width="100%">
					<thead>
						<tr>
							<td class="h5">Dipartimento</td>
							<td class="h5">Tipologia</td>
							<td class="h5">Spazio</td>
							<td class="h5 opt-no-sort">Prenota</td>
							<td class="h5 opt-no-sort">Rimuovi</td>
						</tr>
					</thead>
					<tbody>
						<% @favourite_spaces.each do |favourite_space| %>
							<tr>
								<td><%= favourite_space.dep_name %></td>
								<td><%= favourite_space.typology %></td>
								<td><%= favourite_space.space_name %></td>
								<td>
									<%= form_with url: set_department_path, local: true, method: :post do |form| %>
										<%= form.text_field :selected_dep_name, value: "#{Department.find( Space.find(favourite_space.space_id).department_id).name}", style: 'display: none' %>
										<%= form.text_field :selected_typology, value: "#{favourite_space.typology}", style: 'display: none' %>
										<%= form.text_field :selected_space, value: "#{favourite_space.space_name}", style: 'display: none' %>
										<%= form.text_field :filter, value: "Dep_Typ_Sp", style: 'display: none' %>
										<button class="btn btn-outline-info bi bi-cursor" style="width: 100%"></button>
										<% form.submit '' %>
									<% end %>
								</td>
								<td><%= link_to '', favourite_space, method: :delete, data: { confirm: 'Sei sicuro?' }, class: "btn btn-outline-info bi bi-trash", id: favourite_space.id.to_s, style: "width: 100%" %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

</body>
</html>