config/routes.rb
Rails.application.routes.draw do

  resources :site_current_dates
  resources :temp_deps
  resources :temp_week_days
  resources :temp_sps

  resources :departments
  resources :week_days
  resources :spaces
  resources :seats

  resources :reservations
  resources :quick_reservations
  resources :favourite_spaces

  resources :tasks

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", passwords: "passwords", confirmations: "confirmations", sessions: "sessions" }

  root "home#index"

  # Generali
  get "/home", to: "home#index"
  post '/home', to: 'home#index', as: 'get_meteo_info'
  get "/leaflet_osm_map", to: "leaflet_osm#index"
  get "/personal_area", to: "personal_area#index"
  get "/informations", to: "informations#index"

  # Accessibili dall'area personale utente
  get "/user_reservations", to: "reservations#reserved"
  get "/favourite_spaces", to: "favourite_spaces#index"

  # Admin
  get "/management", to: "management#index"

  # Dipartimenti
  get "/make_department", to: "temp_deps#new"
  post '/make_department', to: 'temp_deps#set_temp_wd', as: 'set_temp_wd'
  get "/manager_department", to: "departments#manager_department"
  post '/manager_department', to: 'departments#manager_map_initializer', as: 'manager_map_initializer'

  # Prenotazioni
  get "/make_reservation", to: "reservations#new"
  post '/make_reservation', to: 'reservations#set_department', as: 'set_department'
  post '/user_reservations', to: 'reservations#make_actions', as: 'make_actions'
  get "/make_quick_res", to: "quick_reservations#make_quick_res"

  post "/find_on_map", to:"home#find_on_map"

  resources :users do       # CONTROLLA LE MAIL DI CONFERMA E IN CASO DI ASSENZA PER NUOVA REGISTRAZIONE NE INVIA UNA (CONTROLLARE application_mailer PER ULTERIORI DETTAGLI)
    member do
      get :confirm_email
      patch :ban
      patch :set_manager
      patch :manager_req
      patch :get_user_coord
    end
  end

  devise_scope :user do     # CONTROLLA IL TIMEOUT DELLA SESSIONE DELL'UTENTE 
    get   "/check_session_timeout"    => "session_timeout#check_session_timeout"
    get   "/session_timeout"          => "session_timeout#render_timeout"
  end

end

app/controllers/personal_area_controller.rb
class PersonalAreaController < ApplicationController
    before_action :authenticate_user!
    helper_method :load_events
    CALENDAR_ID = 'primary'

  def index
    @quick_reservation = QuickReservation.where(user_id: current_user.id).first
  end

    def load_events
      begin
        client = Google::Apis::CalendarV3::CalendarService.new
        client_authorization = Signet::OAuth2::Client.new
        client_authorization.client_id = ENV["GOOGLE_CLIENT_ID"]
        client_authorization.client_secret = ENV["GOOGLE_CLIENT_SECRET"]
        client_authorization.access_token = current_user.access_token
        client_authorization.refresh_token = current_user.refresh_token
        client_authorization.expires_at = current_user.expires_at

        if current_user.expires_at <= Time.now.to_i
          redirect_to "/session_timeout"
        end

        client.authorization = client_authorization
        client.authorization.grant_type = "refresh_token"
        @result = client.list_events(CALENDAR_ID,max_results: 1000,single_events: true,order_by: 'startTime',time_min: Time.now.iso8601) # LEGGO I PROSSIMI 10 EVENTI SUL CALENDAR
        @hash = {} # HASH CHE CONTERRÀ TUTTI GLI EVENTI DEL CALENDAR
        @result.items.each do |event|
          x=[event.summary, event.start.date_time.strftime("%H:%M")]
          print x
          @hash[event.start.date_time.strftime("%Y-%m-%d").to_s]=x # AGGIUNGO GLI EVENTI FORMATTANDONE LA DATA CHE VIENE USATA COME CHIAVE
        end
        return @hash
      rescue => exception
        print "\n\n\n\nERRORE\n",exception,"\n\n\n\n"
      end
    end

end

app/helpers/personal_area_helper.rb
module PersonalAreaHelper
end

app/views/personal_area/index.html.erb
<!DOCTYPE html>
<html lang="it">
<head>

	<title> Area personale - Spacebook </title>

</head>

<body>

	<h2 class="text-white mb-4"> Benvenuto nella tua area personale </h2>

	<div class="row">
		<!-- Calendario per sincronizzazione AL MOMENTO SE SI È COLLEGATI TRAMITE GOOGLE IL CALENDARIO VIENE FORMATO CON I PROSSIMI 10 EVENTI ALL'INTERNO -->
		<div class="col-lg-7 pb-2">
			<div class="card">
				<div class="card-header">
					<% if current_user.access_token != nil %> 
						<label class="h4 bi bi-calendar2-week my-2"> Google Calendar </label>
					<% else %>
						<label class="h4 bi bi-calendar2-week my-2"> Calendario </label>
					<% end %>
				</div>
				<div class="card-body px-3" style="display: flex; align-items: center">
					<% if current_user.access_token!=nil%> <!-- SE IL TOKEN È PRESENTE VIENE INVIATA LA RICHIESTA A CALENDAR -->
						<% @hash=load_events %>
						<% if @hash!=nil %>
							<%= month_calendar do |date| %>
								<%= date.day %>
								<div>
									<% if @hash[date.to_s]!=nil %>
										<font size="-2"><%= @hash[date.to_s][0]%></font>
										<font size="-3" color="blue"><%= @hash[date.to_s][1]%></font>
									<% end %>
								</div>
							<% end %>
						<% else %>
							<%= month_calendar do |date| %> <!-- SE IL CALENDAR DELL'UTENTE NON PRESENTA EVENTI CREA CALENDARIO VUOTO -->
								<%= date.day %>
							<% end %>
						<% end %>
					<% else %>                              <!-- IN CASO L'ACCESSO NON SIA STATO EFFETTUATO TRAMITE GOOGLE VIENE PRODOTTO UN CALENDARIO SENZA EVENTI -->
						<%= month_calendar do |date| %>
							<%= date.day %><br>
							<% Reservation.where(user_id: current_user.id).each do |reservation| %>
								<% if reservation.start_date.strftime("%Y-%m-%d").to_s == date.to_s %>
									<font size="-2"><%= reservation.dep_name %></font>
									<font size="-3" color="blue"><%= reservation.typology %> - <%= reservation.space_name %></font></br>
									<font size="-3" color="blue"><%= reservation.start_date.strftime("%H:%M")%> - <%= reservation.end_date.strftime("%H:%M")%></font>
									<% break %>
								<% end %>
							<% end %>

						<% end %>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-lg-5 pb-2" style="padding-left: 30px">
			<div class="row">
				<!-- Link alle varie pagine -->
				<div class="col-lg-12 pb-4">
					<div class='row'>
						<div class='col-lg-12'>
							<div class="card mb-4">
								<div class="card-header"> 
									<label class="h4 bi bi-person-lines-fill my-2" style="width: 100%"> <%= current_user.email %> </label>
								</div>
							</div>
						</div>
						<div class='col-lg-12'>
							<!-- Card per la prenotazione rapida -->
							<div class="card mb-4">
								<div class="card-header">
									<table width="100%">
										<tr>
											<% if @quick_reservation %>
												<td>
													<label class="h4 mt-1 mb-1"> Prenotazione rapida </label>
													<p class="small mb-0"> <%= (@quick_reservation)? ""+@quick_reservation.dep_name.to_s+": "+@quick_reservation.typology.to_s+"-"+@quick_reservation.space_name.to_s+"" : "Non impostata" %></p>
												</td>
												<td class="px-2">
													<label class="mx-0 my-0 px-0 py-0" style="float: right" type="button" data-bs-toggle="modal" id="modalCaricamentoButton" data-bs-target="#modalCaricamento">
														<a class="btn btn-sm btn-outline-info" onclick="window.location.href='/make_quick_res'"> <i class='bi bi-cursor'></i> <br> Prenota </a>
													</label>
												</td>
											<% else %>
												<td>
													<label class="h4 mt-1 mb-1"> Prenotazione rapida </label>
													<p class="small mb-0"> Non impostata </p>
												</td>
												<td class="px-2">
													<label class="mx-0 my-0 px-0 py-0" style="float: right" type="button" data-bs-toggle="modal" id="modalCaricamentoButton" data-bs-target="#modalCaricamento">
														<a class="btn btn-sm btn-outline-info" style="float: right" onclick="window.location.href='/make_reservation'"> <i class='bi bi-pen'></i> <br> Imposta </a>
													</label>
												</td>
											<% end %>
										</tr>
									</table>
								</div>
							</div>
						</div>
					</div>
					<% if current_user.is_user? && current_user.requested_manager==nil%>
							<%= button_to 'Richiedi il ruolo di Manager', manager_req_user_path(current_user) , method: :patch, class: "btn btn-sm btn-outline-info mb-4", style: "width:100%"%>
					<% end %>
					<div class="row">
						<div class="col-lg-4">
							<div class="card" style="height: 100%; cursor: pointer">
								<div class="card-header px-0 py-0">
									<img class="card-img-top" id="personalAreaImg" src="https://i.pinimg.com/736x/fc/e0/f6/fce0f6027d2fcbbd232fddcd71873f03.jpg">
								</div>
								<div class="card-footer px-2" style="height: 100%">
									<p class="h6 bi bi-list-check my-2"> Le mie prenotazioni </p>
									<a class="stretched-link" onclick="window.location.href='/user_reservations'"></a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="card" style="height: 100%; cursor: pointer">
								<div class="card-header px-0 py-0">
									<img class="card-img-top" id="personalAreaImg" src="https://i.pinimg.com/564x/26/fb/7e/26fb7edd0ac89f5e36d7a98bd6d1873e.jpg">
								</div>
								<div class="card-footer px-2" style="height: 100%">
									<p class="h6 bi bi-bookmark-star my-2"> Spazi preferiti </p>
									<a class="stretched-link" onclick="window.location.href='/favourite_spaces'"></a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="card" style="height: 100%; cursor: pointer">
								<div class="card-header px-0 py-0">
									<img class="card-img-top" id="personalAreaImg" src="https://i.pinimg.com/564x/77/ae/db/77aedb455931b1132ba273846f0c21e4.jpg">
								</div>
								<div class="card-footer px-2" style="height: 100%">
									<p class="h6 bi bi-card-list my-2"> Nuova prenotazione </p>
									<a class="stretched-link" onclick="window.location.href='/make_reservation'"></a>
								</div>
							</div>
						</div>

						<% if current_user.is_manager? %>
							<div class="col-lg-12 pt-4">
								<div class="card" style="cursor: pointer">
									<div class="card-header px-0 py-0">
										<img class="card-img-top" id="personalAreaImg" src="https://i.pinimg.com/564x/9a/d9/46/9ad946ce786180f826b61cce48a1f9c8.jpg">
									</div>
									<div class="card-footer px-3" style="height: 100%">
										<p class="h6 bi bi-building my-2"> Il mio dipartimento </p>
										<a class="stretched-link" onclick="window.location.href='/manager_department'"></a>
									</div>
								</div>
							</div>
						<% elsif current_user.is_admin? %>
							<div class="col-lg-12 pt-4">
								<div class="card" style="cursor: pointer">
									<div class="card-header px-0 py-0">
										<img class="card-img-top" id="personalAreaImg" src="https://i.pinimg.com/564x/75/0d/7c/750d7cc6ea932b46e2a2856c862b6a24.jpg">
									</div>
									<div class="card-footer px-3" style="height: 100%">
										<p class="h6 bi bi-gear-wide-connected my-2"> Gestione sito </p>
										<a class="stretched-link" onclick="window.location.href='/management'"></a>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>	
	</div>

</body>
</html>