config/routes.rb
Rails.application.routes.draw do

  resources :site_current_dates
  resources :temp_deps
  resources :temp_week_days
  resources :temp_sps

  resources :departments
  resources :week_days
  resources :spaces
  resources :seats

  resources :reservations
  resources :quick_reservations
  resources :favourite_spaces

  resources :tasks

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", passwords: "passwords", confirmations: "confirmations", sessions: "sessions" }

  root "home#index"

  # Generali
  get "/home", to: "home#index"
  post '/home', to: 'home#index', as: 'get_meteo_info'
  get "/leaflet_osm_map", to: "leaflet_osm#index"
  get "/personal_area", to: "personal_area#index"
  get "/informations", to: "informations#index"

  # Accessibili dall'area personale utente
  get "/user_reservations", to: "reservations#reserved"
  get "/favourite_spaces", to: "favourite_spaces#index"

  # Admin
  get "/management", to: "management#index"

  # Dipartimenti
  get "/make_department", to: "temp_deps#new"
  post '/make_department', to: 'temp_deps#set_temp_wd', as: 'set_temp_wd'
  get "/manager_department", to: "departments#manager_department"
  post '/manager_department', to: 'departments#manager_map_initializer', as: 'manager_map_initializer'

  # Prenotazioni
  get "/make_reservation", to: "reservations#new"
  post '/make_reservation', to: 'reservations#set_department', as: 'set_department'
  post '/user_reservations', to: 'reservations#make_actions', as: 'make_actions'
  get "/make_quick_res", to: "quick_reservations#make_quick_res"

  post "/find_on_map", to:"home#find_on_map"

  resources :users do       # CONTROLLA LE MAIL DI CONFERMA E IN CASO DI ASSENZA PER NUOVA REGISTRAZIONE NE INVIA UNA (CONTROLLARE application_mailer PER ULTERIORI DETTAGLI)
    member do
      get :confirm_email
      patch :ban
      patch :set_manager
      patch :manager_req
      patch :get_user_coord
    end
  end

  devise_scope :user do     # CONTROLLA IL TIMEOUT DELLA SESSIONE DELL'UTENTE 
    get   "/check_session_timeout"    => "session_timeout#check_session_timeout"
    get   "/session_timeout"          => "session_timeout#render_timeout"
  end

end

app/controllers/leaflet_osm_controller.rb
class LeafletOsmController < ApplicationController
  def index
      @departments = Department.all
  end
end

app/helpers/leaflet_osm_helper.rb
module LeafletOsmHelper
end

app/views/leaflet_osm/index.html.erb
<!-- Pagina Home -->
<!DOCTYPE html>
<html lang="it">
<head>

	<title> Home - Spacebook </title>
	<%= javascript_pack_tag 'leaflet' %>
	<%= stylesheet_link_tag 'leaflet', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'leaflet-routing-machine' %>
	<%= stylesheet_link_tag 'leaflet-routing-machine',media: 'all', 'data-turbolinks-track': 'reload' %> 
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />

	<link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
	<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>

</head>

<body>
    <!-- Mappa per geolocalizzazione -->
    <div class="card mb-4" style="height: 685px">
        <div class="card-header text-center">
            <label class="h2 my-3"> Mappa <i class="bi bi-map mx-2"></i> </label>
        </div>
        <div class="card-body pt-2">
            <label class="h5 mb-0 px-2"> Zoom </label>
            <label class="h5 mb-0 px-2" style="float: right"> Inserisci destinazione e arrivo e premi invio per confermare </label>
            <div id="map" style="height: 95% !important"></div>

            <!-- Utilizzo LEAFLET e OSM per generare una mappa centrata su Roma -->
            <script>
                var map = L.map('map').setView([41.89333, 12.48302], 11);
                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '© OpenStreetMap'
                }).addTo(map);

                var EdIcon = L.icon({
                    iconUrl: '<%=image_path('pin.png')%>',
                    shadowUrl: '<%=image_path('marker-shadow.png')%>',
                    iconSize:     [30, 50], // size of the icon
                    shadowSize:   [30, 64], // size of the shadow
                    iconAnchor:   [17, 58], // point of the icon which will correspond to marker's location
                    shadowAnchor: [9, 75],  // the same for the shadow
                    popupAnchor:  [-3, -60] // point from which the popup should open relative to the iconAnchor
                });
            </script>

            <% @departments.each do |department| %>
                <script>
                    L.marker(["<%=department.latitude%>", "<%=department.longitude%>"],{icon: EdIcon}).addTo(map).bindPopup("<%=department.name%>"+"<br>"+"<%=department.via+" "+department.civico+" "+department.citta+" "+department.cap %>");
                </script>
            <%end%>

            <script>
                document.getElementById("centra").onclick = function() {centra_mappa()};
                function centra_mappa(lat, lon, dep_n, dep, zoom, marker) {
                    map.setView([lat, lon], parseInt(zoom));
                    var myIcon = L.icon({
                        iconUrl: '<%=image_path('marker-icon-2x.png')%>',
                        shadowUrl: '<%=image_path('marker-shadow.png')%>',
                        iconSize:     [30, 50], // size of the icon
                        shadowSize:   [30, 64], // size of the shadow
                        iconAnchor:   [17, 58], // point of the icon which will correspond to marker's location
                        shadowAnchor: [9, 75],  // the same for the shadow
                        popupAnchor:  [-3, -60] // point from which the popup should open relative to the iconAnchor
                    });
                    if (marker=='true'){
                        L.marker([lat, lon],{icon: myIcon}).addTo(map).bindPopup(dep_n+"<br>"+dep).openPopup();
                    }
                }
            </script>

            <script>
                L.Routing.control({
                    waypoints: [ L.latLng(), L.latLng() ],
                    routeWhileDragging: true,
                    geocoder: L.Control.Geocoder.nominatim(),
                }).addTo(map);
            </script>
        </div>
        <div class="card-footer">
            <% if current_user %>
                <%= button_to 'Cerca intorno a te', get_user_coord_user_path(current_user) , method: :patch, class: "btn btn-sm btn-outline-info my-1", style: "width:100%"%>
            <% end %>
        </div>
    </div>
</body>
</html>