config/routes.rb
Rails.application.routes.draw do

  resources :site_current_dates
  resources :temp_deps
  resources :temp_week_days
  resources :temp_sps

  resources :departments
  resources :week_days
  resources :spaces
  resources :seats

  resources :reservations
  resources :quick_reservations
  resources :favourite_spaces

  resources :tasks

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", passwords: "passwords", confirmations: "confirmations", sessions: "sessions" }

  root "home#index"

  # Generali
  get "/home", to: "home#index"
  post '/home', to: 'home#index', as: 'get_meteo_info'
  get "/leaflet_osm_map", to: "leaflet_osm#index"
  get "/personal_area", to: "personal_area#index"
  get "/informations", to: "informations#index"

  # Accessibili dall'area personale utente
  get "/user_reservations", to: "reservations#reserved"
  get "/favourite_spaces", to: "favourite_spaces#index"

  # Admin
  get "/management", to: "management#index"

  # Dipartimenti
  get "/make_department", to: "temp_deps#new"
  post '/make_department', to: 'temp_deps#set_temp_wd', as: 'set_temp_wd'
  get "/manager_department", to: "departments#manager_department"
  post '/manager_department', to: 'departments#manager_map_initializer', as: 'manager_map_initializer'

  # Prenotazioni
  get "/make_reservation", to: "reservations#new"
  post '/make_reservation', to: 'reservations#set_department', as: 'set_department'
  post '/user_reservations', to: 'reservations#make_actions', as: 'make_actions'
  get "/make_quick_res", to: "quick_reservations#make_quick_res"

  post "/find_on_map", to:"home#find_on_map"

  resources :users do       # CONTROLLA LE MAIL DI CONFERMA E IN CASO DI ASSENZA PER NUOVA REGISTRAZIONE NE INVIA UNA (CONTROLLARE application_mailer PER ULTERIORI DETTAGLI)
    member do
      get :confirm_email
      patch :ban
      patch :set_manager
      patch :manager_req
      patch :get_user_coord
    end
  end

  devise_scope :user do     # CONTROLLA IL TIMEOUT DELLA SESSIONE DELL'UTENTE 
    get   "/check_session_timeout"    => "session_timeout#check_session_timeout"
    get   "/session_timeout"          => "session_timeout#render_timeout"
  end

end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  before_action :authenticate_user!

  # Pagina di gestione del sito da parte degli admin
  def index

    if(current_user.is_admin?) # Blocca l'accesso alla pagina se non si è amministratori

      @usr = User.ransack(params[:q])
      @users = @usr.result(distinct: true)

      @dep = Department.ransack(params[:q])
      @departments = @dep.result(distinct: true)

      @res = Reservation.ransack(params[:q])
      @reservations = @res.result(distinct: true)

    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "Attenzione: per gestire il sito devi essere un amministratore!"
    end
  end

end

app/helpers/management_helper.rb
module ManagementHelper
end

app/views/management/index.html.erb
<!DOCTYPE html>
<html lang="it">
<head>

	<title> Gestione sito - Spacebook </title>

	<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
	<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap.min.css">

	<script>
		$(document).ready(function () {
			$('#datatableUtenti').DataTable({
				dom: '<"row"<"col"t>><"row mt-1"<"col"p>>',
				scrollX: true,
				filter: 'false',
				pagingType: "simple_numbers",
				pageLength: 5,
				language: {
					zeroRecords: 'Nessun utente',
					paginate: {
						first:    '<i class="bi bi-caret-left-fill"></i>',
						previous: '<i class="bi bi-arrow-left-circle"></i>',
						next:     '<i class="bi bi-arrow-right-circle"></i>',
						last:     '<i class="bi bi-caret-right-fill"></i>'
					}
				}
			});
		});
	</script>
	<script>
		$(document).ready(function () {
			$('#datatableDipartimenti').DataTable({
				dom: '<"row"<"col"t>><"row mt-1"<"col"p>>',
				scrollX: true,
				filter: 'false',
				pagingType: "simple_numbers",
				pageLength: 5,
				language: {
					zeroRecords: 'Nessun dipartimento',
					paginate: {
						first:    '<i class="bi bi-caret-left-fill"></i>',
						previous: '<i class="bi bi-arrow-left-circle"></i>',
						next:     '<i class="bi bi-arrow-right-circle"></i>',
						last:     '<i class="bi bi-caret-right-fill"></i>'
					}
				}
			});
		});
	</script>
	<script>
		$(document).ready(function () {
			$('#datatablePrenotazioni').DataTable({
				dom: '<"row"<"col"t>><"row mt-1"<"col"p>>',
				scrollX: true,
				filter: 'false',
				pagingType: "simple_numbers",
				pageLength: 5,
				language: {
					zeroRecords: 'Nessuna prenotazione',
					paginate: {
						first:    '<i class="bi bi-caret-left-fill"></i>',
						previous: '<i class="bi bi-arrow-left-circle"></i>',
						next:     '<i class="bi bi-arrow-right-circle"></i>',
						last:     '<i class="bi bi-caret-right-fill"></i>'
					}
				}
			});
		});
	</script>

</head>


<body>

	<div class="card mb-4">
		<div class="card-header">
			<div class="row">
				<div class="col">
					<label class="h4 ml-2 my-3"> Utenti </label>
				</div>
				<div class="col pt-1" style="text-align: right">
					<%= search_form_for(@usr, url: management_path, method: :get, class: "d-none d-md-inline-block form-inline mt-2") do |f| %>
						<table width="100%">
							<tr>
								<td><%= f.search_field :email_i_cont_any, class: "form-control", placeholder: "Cerca tramite email...", id: "Search"%></td>
								<td width="10%"><button class="btn btn-outline-info bi bi-search mx-2"><% f.submit "" %></button></td>
							</tr>
						</table>
					<% end %>
				</div>
			</div>
		</div>
		<div class="card-body">
			<table id="datatableUtenti" class="display table-responsive table-striped table-hover" width="100%">
				<thead>
					<td class="h5" width="25%"> Email </td>
					<td class="h5" width="20%"> Ruolo </td>
					<td class="h5" width="25%"> Motivo blocco </td>
					<td class="h5 opt-no-sort" width="15%"> Blocca/Sblocca </td>
					<td class="h5 opt-no-sort" width="15%"> Rendi manager </td>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<% if current_user.email != user.email%>
							<tr>
								<td><%= user.email %></td>
								<td><%= user.role %></td>
								<% if user.access_locked? %>
									<% if user.locking_reason == nil %>
										<td> Tentativi di accesso esauriti </td>
									<% else %>
										<td> <%= user.locking_reason %> </td>
									<% end %>
								<% else %>
									<td></td>
								<% end %>
								<% if user.role!='admin'%>
									<td><%= button_to ban_status(user), ban_user_path(user) , method: :patch, id:user.id.to_s+ban_status(user), class: "btn btn-sm btn-outline-info", style: "width:100%"%></td>
									<td><%= button_to manager_status(user), set_manager_user_path(user) , method: :patch, class: "btn btn-sm btn-outline-info", style: "width:100%"%></td>
								<% else %>
									<td></td>
									<td></td>
								<% end %>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	<div class="card mb-4">
		<div class="card-header">
			<div class="row">
				<div class="col">
					<label class="h4 ml-2 my-3"> Dipartimenti </label>
				</div>
				<div class="col pt-1" style="text-align: right">
					<%= search_form_for(@dep, url: management_path, method: :get, class: "d-none d-md-inline-block form-inline mt-2") do |f| %>
						<table width="100%">
							<tr>
								<td><%= f.search_field :name_or_via_or_civico_or_cap_or_citta_or_provincia_or_manager_i_cont_any, class: "form-control", placeholder: "Cerca un dipartimento...", id: "Search"%></td>
								<td width="10%"><button class="btn btn-outline-info bi bi-search mx-2"><% f.submit "" %></button></td>
							</tr>
						</table>
					<% end %>
				</div>
			</div>
		</div>
		<div class="card-body">
			<table id="datatableDipartimenti" class="display table-responsive table-striped table-hover" width="100%">
				<thead>
					<tr>
						<td class="h5" width="25%"> Nome </td>
						<td class="h5" width="20%"> Email del manager </td>
						<td class="h5" width="25%"> Indirizzo </td>
						<td class="h5 opt-no-sort" width="15%"> Mostra </td>
						<td class="h5 opt-no-sort" width="15%"> Elimina </td>
					</tr>
				</thead>
				<tbody>
					<% @departments.each do |department| %>
						<tr>
							<td><%= department.name %></td>
							<td><%= department.manager %></td>
							<td><%= department.via %>, <%= department.civico %>, <%= department.cap %>, <%= department.citta %>, <%= department.provincia %></td>
							<td><%= link_to '', department, method: :get, class: "btn btn-sm btn-outline-info bi bi-eye", style: "width:100%"%>
							<td><%= link_to '', department, method: :delete, data: { confirm: 'Sicuro?' }, class: "btn btn-sm btn-outline-info bi bi-trash", style: "width:100%"%>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	<div class="card mb-4">
		<div class="card-header">
			<div class="row">
				<div class="col">
					<label class="h4 ml-2 my-3"> Prenotazioni </label>
				</div>
				<div class="col pt-1" style="text-align: right">
					<%= search_form_for(@res, url: management_path, method: :get, class: "d-none d-md-inline-block form-inline mt-2") do |f| %>
						<table width="100%">
							<tr>
								<td><%= f.search_field :email_or_dep_name_or_typology_or_space_name_or_state_i_cont_any, class: "form-control", placeholder: "Cerca una prenotazione...", id: "Search"%></td>
								<td width="10%"><button class="btn btn-outline-info bi bi-search mx-2"><% f.submit "" %></button></td>
							</tr>
						</table>
					<% end %>
				</div>
			</div>
		</div>
		<div class="card-body">
			<table id="datatablePrenotazioni" class="display table-responsive table-striped table-hover" width="100%">
				<thead>
					<tr>
						<td class="h5" width="20%"> Utente </td>
						<td class="h5" width="20%"> Dipartimento </td>
						<td class="h5" width="15%"> Tipologia </td>
						<td class="h5" width="15%"> Spazio </td>
						<td class="h5" width="5%"> Piano </td>
						<td class="h5" width="5%"> Posto </td>
						<td class="h5" width="10%"> Data </td>
						<td class="h5" width="20%"> Orario </td>
						<td class="h5" width="5%"> Stato </td>
						<td class="h5 opt-no-sort" width="5%"> Elimina </td>
					</tr>
				</thead>
				<tbody>
					<% @reservations.each do |reservation| %>
						<tr>
							<td><%= reservation.email %></td>
							<td><%= reservation.dep_name %></td>
							<td><%= reservation.typology %></td>
							<td><%= reservation.space_name %></td>
							<td><%= reservation.floor %></td>
							<td><%= reservation.seat_num %></td>
							<td><%= reservation.start_date.mday %>-<%= reservation.start_date.mon %>-<%= reservation.start_date.year %></td>
							<td><%= reservation.start_date.strftime('%H:%M') %> - <%= reservation.end_date.strftime('%H:%M') %> </td>
							<td><%= reservation.state %></td>
							<td><%= link_to '', reservation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-info bi bi-trash", style: "width: 100%"%></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

</body>
</html>